### ISSUE TITLE
Vercel Error

### ISSUE THREAD

**Issue by jennjunod** [Teach-Jenn-Tech/website#27]
https://portfolio-nkup5xg9q-teachjenntech.vercel.app

```
Could not resolve '../config' from src/pages/rss.xml.js
--
09:49:33.098 | error   Could not resolve '../config' from src/pages/rss.xml.js
09:49:33.098 | Error: Could not resolve '../config' from src/pages/rss.xml.js
09:49:33.098 | at error (file:///vercel/path0/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
09:49:33.098 | at ModuleLoader.handleResolveId (file:///vercel/path0/node_modules/rollup/dist/es/shared/rollup.js:22156:24)
09:49:33.099 | at file:///vercel/path0/node_modules/rollup/dist/es/shared/rollup.js:22119:26
09:49:33.523 | Error: Command "npm run build" exited with 1
```

**Comment by jennjunod** [comment]
YAY fixed...

Moved `rss.xml.js` to `keep` folder which helped with it not being read, doesn't seem to be causing issues with it not being there. 

Next issue was `src/layouts/BlogPost.astro`

`---
import BaseHead from '../components/BaseHead.astro';
import Header from '../components/Header.astro';
import Footer from '../components/Footer.astro';
import Header from '~/components/header.astro';
import Footer from '~/components/footer.astro';
export interface Props {
	content: {`
